"""changed_type

Revision ID: 0a9fc5b709d2
Revises: 43930a848362
Create Date: 2024-07-27 04:30:11.175025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a9fc5b709d2"
down_revision: Union[str, None] = "43930a848362"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trades",
        "prediction_end_date",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Date of prediction to be ended, Miner can no longer predict after this date for this txn",
        existing_nullable=False,
        postgresql_using="prediction_end_date::timestamp with time zone",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trades",
        "prediction_end_date",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.VARCHAR(),
        existing_comment="Date of prediction to be ended, Miner can no longer predict after this date for this txn",
        existing_nullable=False,
        postgresql_using="prediction_end_date::text",
    )
    # ### end Alembic commands ###
