"""update_answer_table

Revision ID: 16d0fd7ff8c0
Revises: 29daf7aaa257
Create Date: 2024-08-04 23:40:29.600808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16d0fd7ff8c0'
down_revision: Union[str, None] = '29daf7aaa257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('validations', sa.JSON(), nullable=True))
    op.drop_column('answers', 'validator_ids')
    op.add_column('subnet_users', sa.Column('module_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'subnet_users', ['module_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subnet_users', type_='unique')
    op.drop_column('subnet_users', 'module_id')
    op.add_column('answers', sa.Column('validator_ids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('answers', 'validations')
    # ### end Alembic commands ###
