"""init_db

Revision ID: 29daf7aaa257
Revises: 
Create Date: 2024-08-04 13:27:02.972197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29daf7aaa257'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('question_type', postgresql.ENUM('multiple_choice', 'true_false', 'short_answer', name='question_types'), nullable=False),
    sa.Column('answer_choices', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_updated_at'), 'questions', ['updated_at'], unique=False)
    op.create_table('subnet_users',
    sa.Column('user_address', sa.String(), nullable=False),
    sa.Column('user_type', postgresql.ENUM('validator', 'miner', name='user_types'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subnet_users_created_at'), 'subnet_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_subnet_users_id'), 'subnet_users', ['id'], unique=False)
    op.create_index(op.f('ix_subnet_users_updated_at'), 'subnet_users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_subnet_users_user_address'), 'subnet_users', ['user_address'], unique=True)
    op.create_table('answers',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('answerer_id', sa.UUID(), nullable=False),
    sa.Column('validator_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('supporting_resources', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_created_at'), 'answers', ['created_at'], unique=False)
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_index(op.f('ix_answers_updated_at'), 'answers', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_updated_at'), table_name='answers')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_created_at'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_subnet_users_user_address'), table_name='subnet_users')
    op.drop_index(op.f('ix_subnet_users_updated_at'), table_name='subnet_users')
    op.drop_index(op.f('ix_subnet_users_id'), table_name='subnet_users')
    op.drop_index(op.f('ix_subnet_users_created_at'), table_name='subnet_users')
    op.drop_table('subnet_users')
    op.drop_index(op.f('ix_questions_updated_at'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
