"""added_extra_status_module_id_tempo_table

Revision ID: 5ba8d790bd44
Revises: da3886f4fc4d
Create Date: 2024-07-29 03:00:14.201948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba8d790bd44'
down_revision: Union[str, None] = 'da3886f4fc4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempo',
    sa.Column('current_tempo_end_date', sa.DateTime(), nullable=False),
    sa.Column('future_tempo_end_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tempo_created_at'), 'tempo', ['created_at'], unique=False)
    op.create_index(op.f('ix_tempo_id'), 'tempo', ['id'], unique=False)
    op.create_index(op.f('ix_tempo_updated_at'), 'tempo', ['updated_at'], unique=False)
    op.add_column('trades', sa.Column('token_address', sa.String(), nullable=False))
    op.add_column('trades', sa.Column('closeness_value', sa.Float(), nullable=True, comment='Closeness value of the prediction, i.e. actual price - predicted price'))
    op.add_column('trades', sa.Column('module_id', sa.String(), nullable=False, comment='Module ID of the miner/validator in commune subnet'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'module_id')
    op.drop_column('trades', 'closeness_value')
    op.drop_column('trades', 'token_address')
    op.drop_index(op.f('ix_tempo_updated_at'), table_name='tempo')
    op.drop_index(op.f('ix_tempo_id'), table_name='tempo')
    op.drop_index(op.f('ix_tempo_created_at'), table_name='tempo')
    op.drop_table('tempo')
    # ### end Alembic commands ###
