"""added_signal_column

Revision ID: 7f439d30ae6b
Revises: d420e6c64761
Create Date: 2024-07-26 01:47:46.924507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7f439d30ae6b"
down_revision: Union[str, None] = "d420e6c64761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    trade_signal_enum = postgresql.ENUM(
        "bullish", "bearish", name="trade_signal", create_type=True
    )
    trade_signal_enum.create(op.get_bind())
    op.add_column(
        "trades",
        sa.Column(
            "signal", trade_signal_enum, nullable=True, comment="Signal for the trade"
        ),
    )
    op.alter_column(
        "trades",
        "predicted_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Price predicted by the miner",
        existing_nullable=True,
    )
    op.alter_column(
        "trades",
        "prediction_end_date",
        existing_type=sa.VARCHAR(),
        comment="Date of prediction to be ended, Miner can no longer predict after this date for this txn",
        existing_nullable=False,
    )
    op.alter_column(
        "trades",
        "roi",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Return on investment",
        existing_nullable=True,
    )
    op.alter_column(
        "trades",
        "actual_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Actual price of the token on prediction date",
        existing_nullable=True,
    )
    op.alter_column(
        "trades",
        "price_prediction_date",
        existing_type=postgresql.TIMESTAMP(),
        comment="Date of prediction to be happened",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trades",
        "price_prediction_date",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Date of prediction to be happened",
        existing_nullable=False,
    )
    op.alter_column(
        "trades",
        "actual_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Actual price of the token on prediction date",
        existing_nullable=True,
    )
    op.alter_column(
        "trades",
        "roi",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Return on investment",
        existing_nullable=True,
    )
    op.alter_column(
        "trades",
        "prediction_end_date",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Date of prediction to be ended, Miner can no longer predict after this date for this txn",
        existing_nullable=False,
    )
    op.alter_column(
        "trades",
        "predicted_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Price predicted by the miner",
        existing_nullable=True,
    )
    op.drop_column("trades", "signal")
    trade_signal_enum = postgresql.ENUM("bullish", "bearish", name="trade_signal")
    trade_signal_enum.drop(op.get_bind())
    # ### end Alembic commands ###
