"""init_db

Revision ID: d46c570d000c
Revises: 
Create Date: 2024-07-24 16:18:03.330900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd46c570d000c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('feeder_address', sa.String(), nullable=False),
    sa.Column('token_name', sa.String(), nullable=False),
    sa.Column('token_symbol', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('predicted_price', sa.Float(), nullable=True),
    sa.Column('predictor_address', sa.String(), nullable=True),
    sa.Column('validator_address', sa.String(), nullable=True),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('prediction_end_date', sa.String(), nullable=False),
    sa.Column('trading_pair', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('feeded', 'predicted', 'validated', name='trade_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_updated_at'), 'trades', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_updated_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
