"""changed_token_price_names

Revision ID: da3886f4fc4d
Revises: 0a9fc5b709d2
Create Date: 2024-07-27 14:17:12.273942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3886f4fc4d'
down_revision: Union[str, None] = '0a9fc5b709d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('token_price_on_prediction_day', sa.Float(), nullable=True, comment='Actual price of the token on prediction date'))
    op.add_column('trades', sa.Column('token_price_on_trade_day', sa.Float(), nullable=False, comment='Price of the token at the time of trading'))
    op.drop_column('trades', 'actual_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('actual_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Actual price of the token on prediction date'))
    op.drop_column('trades', 'token_price_on_trade_day')
    op.drop_column('trades', 'token_price_on_prediction_day')
    # ### end Alembic commands ###
