name: CI/CD Pipeline

on:
  push:
    branches:
      - feat/initial-phase

jobs:
  build-and-deploy:
    
    environment: deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to remote server
      if: success()
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script:  |
            export PATH=${{ secrets.PATH }}:$PATH
            bash -c "/data/cicd/fastAPI.sh"
